# Generated by Django 4.1.5 on 2023-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('deatil', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
